services:
  ratings:
    build: .
    image: ghcr.io/angellllegna/bookinfo-ratings:dev
    ports:
     -  "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: password123
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    # ports:
      #   "270717:270717"
    volumes:
      - "./databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: ratings
